#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Apr 02 14:50:27 JST 2025
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1743573027500
maven-metadata-tamacat.org.xml.lastUpdated=1743573027499
maven-metadata-tamacat.org.xml.error=
